README.md

This is a typo-level change. Thanks for the cool theme!

Fix link to GTK theme in README

---

README.md
docs/README.md
docs/specs.md

the assets also work without this change but in future this change will
eventually be required, when some assets are changed while the features
(or colors or whatever) are still in the dev branch only: this would
result in assets from the dev branch conflicting with the content of the
main branch
Signed-off-by: brvn0 <me@brvn0.de>

fix: use main branch for assets

---

README.md

This PR changes sorts the README in alphabetical order, normalizes the list style, fixes a typo in the Palettes section.
The total line count changed by 2, since I inserted 2 blank lines before “Search engines” and “Extensions”.

docs: sort readme, normalize lists, fix spelling

---

README.md

The [vercel demo app](http://ctp-codemirror.vercel.app/) mentioned in repo description is linked to my fork. Feel free to remove it. 
Closes #1733

docs: add catppuccin/codemirror

---

README.md

As requested by some members of the community, this PR adds a showcase section to the main README. 
Catppuccin is all about community and the @catppuccin/staff agree that it's a great idea to host a place on our docs to showcase the lovely applications and tools that people are creating with our palette, outside of the amazing ports.
I've included an initial entry from @Everduin94 with their app as they previously mentioned this idea on our discord. (Hope that's okay!)

docs(README): add showcase

---

resources/ports.schema.json
resources/ports.yml

This will add autocompletion for the `resources/ports.yml` file, as well as keep track of more metadata for each port, such as:
- supported operating systems
- whether the port is a userstyle
- category assigned in the README
The end goal is for the ports.yml to auto-generate the Ports section in our README.

feat: add ports.yml schema & add info to conform to the schema

---

.github/DISCUSSION_TEMPLATE/port-requests.yml

Making use of [discussion templates](https://docs.github.com/en/discussions/managing-discussions-for-your-community/creating-discussion-category-forms) which is now in limited public beta

feat: add discussion template

---

README.md
resources/ports.yml

Actually adds it to the Showcase section, followup for #1932.
I forgot that this part of the README is auto-generated as well.

docs(showcase): add Simple MP

---

README.md
resources/generate/deno.lock
resources/generate/deps.ts

Fixing a remnant of Deno 1.29 being broken with this library.

fix(build): use npm import for ajv

---

resources/ports.yml

As discussed on discord, the youtube-music userstyle has separate css files and supports desktop clients alongside stylus. As this is now similar to the discord port which we are currently not including, we should not label this as a userstyle.
We may come back and revisit this decision at a later point in time.

docs: youtube-music is not a userstyle

---

README.md

> Personally, the section of the docs called palette serves too similar of a purpose to usage and I know they are technically different but without a doubt they could be combined. I am starting this discussion to see what other people think of this.
~ @isabelroses 
As discussed over on Discord – here is a porposal for the unification. c:

docs(readme): unify palette & usage

---

docs/port-creation.md

While making my first port, I was advised by @nekowinston to use the following git line to "squash" previous commits to a new initial commit
`git reset $(git commit-tree HEAD^{tree} -m "init: Start new port")` poking around stack overflow, this seems like the conventional way to go about this
This might be common knowledge and I just don't know a better way, but it may be worth adding as a step in the template cloning process

docs: add step to delete existing `.git` history

---

README.md
docs/port-creation.md
resources/generate/deno.lock
resources/generate/deps.ts
resources/generate/main.ts
resources/generate/types.d.ts
resources/ports.schema.json
resources/ports.yml

This PR supersedes #1981.
I've updated the documentation to clarify what userstyles are if people are looking to create their own ports, as well as using @rubyowo's existing code to pull in metadata from the https://github.com/catppuccin/userstyles repository to link our userstyles.
It's worth mentioning that the CI hasn't been updated to trigger rebuilds off changes to the userstyles repository as @nekowinston is interested in doing this work. In addition to this, I was experimenting with the mermaid diagram by trying to include the userstyle steps. Unfortunately, it's not formatted well so I've chosen to omit it for now. 
You can see what it currently looks like below:
```mermaid
stateDiagram-v2
idea: You have an idea for a port
idea --> choice
choice: Have you already completed a …
```

build: retrieve userstyles from `catppuccin/userstyles`

---

resources/ports.yml

I thought for professionalism and consistency, it would be good to capitalize RemNote's name according to their advertising in the main file. 
- `ports.yml`

✏️ typo(remnote): properly capitalize RemNote's Name

---

resources/ports.yml

To close https://github.com/catppuccin/catppuccin/issues/2111
Transferred repo: https://github.com/catppuccin/halloy
(Not clear if the `color` and `icon` fields are meant to be used or where they are displayed).

docs: add catppuccin/halloy

---

README.md
resources/ports.yml

Meowix Linux is discontinued, see [here](https://github.com/Meowix-Linux/Meowix-ISO/discussions/11)

Remove Meowix Linux from README.md

---

resources/ports.yml

Hi!
Port has been already transferred to the org: [catppuccin/simplex](https://github.com/catppuccin/simplex)
Closes #2144
Thanks in advance!

docs: add catppuccin/simplex

---

resources/ports.yml

This is no longer required in the main repository as `catppuccin/userstyles` tracks it.

chore(ports.yaml): remove `startpage`

---

resources/ports.yml

Yazi can be run on Android, https://github.com/termux/termux-packages/blob/master/packages/yazi/build.sh
I added Android to the first position since its first letter is `a` - if this is not the correct order, please let me know, and I'll fix it :)

chore: add platform `android` for Yazi

---

resources/ports.yml

This is now tracked over at [catppuccin/userstyles](https://github.com/catppuccin/userstyles/blob/331932b2b62dd11d5ad9d0f2a597fdfa84e8831c/scripts/userstyles.yml#L235-L240)

chore(ports.yml): remove `duckduckgo`

---

README.md

this change fixes the eggs that form when the readme is squashed horizontally.
previous behaviour:
new behaviour:
i'm not sure this is best practice, but given these are very small images, in a table, and in a collapsed section by default, i don't think layout concerns are as important here as they otherwise could be. at the very least it seems like a decent compromise until we can just link to the website instead.

docs(README.md): remove `height` on palette circles

---

resources/ports.yml

Driven by the recent work on the [Catppuccin Website](https://catppuccin-website.vercel.app/).
This PR combs through all defined ports and explicitly defines icons where there is one from [Simple Icons](https://simpleicons.org/), also updates icons/colours for icons that have been added since they were ported to Catppuccin.
Still need to check some stuff so raising as a draft PR for now.

refactor(ports.yml): update/add port icons

---

docs/port-creation.md

the current link does not apply the template due to an errant `+` where a `-` should be

docs(port-creation): fix port review issue link

---

docs/style-guide.md

This PR focuses on updates to the code editors:
- Selection Background: Change from `Surface 2` to `Overlay 2`
- Symbols, Atoms: `Red`
- Comments: Suggest `Overlay 2` instead of `Overlay 0`
- Cursor Line:  `Text` 10% Opacity
- Line Numbers: `Overlay 1`
- Active Line Number: `Lavender` (To be updated with accent colour later)
- Property Tags (JSON, YAML, TOML, etc): `Blue`
- Attributes (XML, etc): `Yellow`
~~The indentation has also been updated to be consistent, ideally would be in a separate PR but I accidentally committed all the changes. I plan to merge this PR with a descriptive commit message to make up for the messy diff.~~

docs(style-guide): general updates

---

resources/ports.yml

Updates the name from "ShikiJS" -> "Shiki" and uses a color more in line with the project's branding.

docs: update shiki port metadata

---

resources/ports.yml

Match the definitions in [catppuccin/userstyles@23b8583/scripts/userstyles.yml#L531-L532](https://github.com/catppuccin/userstyles/blob/23b8583c410e78733476d51e196ae2eb4695adc6/scripts/userstyles.yml#L531-L532)

chore: update icon & colour for `nix`

---

resources/ports.yml

Simple Icons now has an icon for bat included (as of v11.12.0), and looking at the color of their icon in the README and on Simple Icons' website it seems `blue` is more accurate. We may have to make sure Simple Icons is updated in the website repository before merging this? Not sure how that works.

docs: update bat icon and color

---

README.md
resources/generate/main.ts
resources/ports.schema.json
resources/ports.yml
resources/types/ports.d.ts

Closes #2409 
Outstanding questions:
- Do we want to display the archived repositories on the README in this repository? The future goal is to point everyone to our website so I didn't bother touching the deno code.
- I thought about adding an `archive_kind` enum but just opted for a simple string to track the reasoning, maybe worth revisiting.

feat: track archived ports

---

resources/ports.yml

Adds an icon for Squirrel/Rime and uses the upstream Anki icon instead of our custom one.

chore(ports.yml): update anki & rime icons

---

resources/ports.yml

We already use the parent organization of suckless's icon for `st`, one of their projects, so it makes sense to also do it for `dmenu`, another one of theirs. #2447 should also be added with the suckless icon.

chore(ports.yml): add suckless icon for dmenu

---

README.md
resources/ports.yml

This was unintentionally removed as the extension
wasn't added to the showcases section within the
ports.yml file.

chore: re-add `Catppuccin Noctis Icons` to showcase

---

resources/ports.yml

This package is now included within catppuccin/python,
therefore the catppuccin/matplotlib repository has
been archived.

docs: alias/archive catppuccin/matplotlib

---

CONTRIBUTING.md

fixes a link thats going to a folder (or a branch) that doesn't exist anymore

docs(CONTRIBUTING): prepend `https://` to link

---

resources/ports.yml

some emojis require having `Variation Selector-16` to be rendered correctly (on my device at least)
from [wikipedia](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)):
> VS15 and VS16 are reserved to request that a character should be displayed as text or as an [emoji](https://en.wikipedia.org/wiki/Emoji) respectively.
for example this is how `🕹 🕹️` appears for me
the first one is [just a joystick](https://apps.timwhitlock.info/unicode/inspect?s=%F0%9F%95%B9) but the second one [contains `Variation Selector-16`](https://apps.timwhitlock.info/unicode/inspect?s=%F0%9F%95%B9%EF%B8%8F)
this is probably required for all emojis listed [here](https://www.unicode.org/emoji/charts/emoji-variants.html)
some emojis in ports.yml weren't being rendered correctly for me so i replaced …

fix(categories): ensure all emojis have `Variation Selector-16`

---

resources/ports.yml

This adds Ghidra to `ports.yml`.

docs: add catppuccin/ghidra

---

resources/ports.yml

This person reached out and let me know that they are no longer interested in
maintaining the nvim port.
Thanks to them for all their work on it!

chore(nvim): move `mrtnvgr` to past-maintainers

---

resources/ports.yml

As mentioned in https://github.com/catppuccin/codemirror/pull/6.

chore(codemirror): remove @uncenter from current-maintainers

---

resources/ports.schema.json
resources/ports.yml
resources/types/ports.d.ts

I was finding that this field was inconsistent sometimes if the
collaborator was both in the `userstyles.yml` and `ports.yml`. Just
simplifying it to one `url` field for now.
At some point in the future, might get rid of the `url` field entirely
and instead rely on the GitHub API, but I'd rather not introduce a
build time task for retrieving the names of the maintainers right now.

refactor(ports.yml): remove nickname from `collaborators`

---

resources/ports.yml

Part of https://github.com/catppuccin/github-file-explorer-icons/issues/109. Will need to rename repository too.

docs: rename github-file-explorer-icons to web-file-explorer-icons

---

resources/ports.yml

Hey @Sourcastic 👋,
I noticed that you haven't been able to dedicate time to Catppuccin (which is fine!) but I think it makes sense to deem KDE as unmaintained.
I'll merge as is but feel free to reach out afterwards in this PR or in discord if you want to chat more.

chore(kde): move @Sourcastic to `past-maintainers`

---

resources/ports.yml

They have deleted their GitHub account so removed the anchor.

chore(sent): remove `xzi` as maintainer

---

resources/ports.yml

A simple yet highly configurable set of widgets for Rainmeter, featuring 18 widgets and 14 themes (including all Catppuccin flavors). Unlike many other skins, the entire configuration is handled through a single `settings.inc` file, designed to be as clean and minimalistic as possible.

docs(showcase): add ccrs

---

resources/ports.schema.json
resources/ports.yml
resources/types/ports.d.ts

Our datasources now rely on the WIP `portscelain` branch which is friendlier to ingest for machines, meaning that we can simplify this file to be easier to edit for humans.

refactor(ports.yml): remove raw GitHub links
