- README.md
Add WezTerm to the list.
The colorshceme for WezTerm (issue#17) is done, tested and online.
> Update list of terminals

- README.md
> feat: added contour

- README.md
> feat: added discord

- .editorconfig
> feat: fix typo

- README.md
> add GRUB theme

- README.md
> Add Chrome

- README.md
Created Mailspring theme - I think it is ready to publish.
> add Mailspring

- README.md
add Papirus Icon Theme Folders with Catppuccin Palette
> add Papirus Icon Theme Folders and Mouse Cursors

- README.md
If I need to pull request it into the dev branch I will. Just leave a comment. 
This is a combined pull request of (SDDM, LXQT) and Alfred
> Added Alfred, SDDM and LXQT ports

- README.md
new theme with 0.2.0 colours: https://github.com/catppuccin/spotify-player
> add spotify-player

- README.md
Many ports are under browser in my option this should only be used for web browsers
> Add Extentions and Search engines catagory

- README.md
> docs: add bat

- docs/contributing.md
makes it more clear what `<emoji>` and `<app>` should be
> docs(contributing): explain emoji usage

- README.md
add PyRadio link to Readme in Dev branch
> docs: add catppuccin/pyradio

- README.md
> **Note**: I love the look of these!
> docs: add note icon to more notes

- README.md
add catppuccin/minecraft to the list of ports
> docs: add catppuccin/minecraft

- README.md
Added foliate to productivity list.
> feat(docs): add foliate

- README.md
Adds a style for startpage.com search engine
> docs: Add Startpage

- README.md
> add youtube music

- docs/specs.md
I noticed while going through the docs that there were a couple of misspellings and such, so I fixed them
> quick grammar fixes

- README.md
> docs: add catppuccin/dwarf-fortress

- README.md
repo: https://github.com/catppuccin/bemenu
original pr: https://github.com/catppuccin/catppuccin/issues/1735
> docs: add catppuccin/bemenu

- README.md
> docs: add catpuccin/home-assistant

- README.md
> docs: add catppuccin/plymouth

- README.md
Repo: https://github.com/sakkke/github-readme-tech-stack
Original PR: #1754
> docs: catppuccin/github-readme-tech-stack

- README.md
> docs: add catppuccin/nighttab

- README.md
- resources/ports.yml
> docs: add catppuccin/modrinth

- README.md
- resources/ports.yml
> docs: add catppuccin/brave-search

- README.md
- resources/ports.yml
💖💖✨🥺,👉👈💖💖,,,,👉👈💖💖🥺👉👈💖💖✨🥺👉👈✨✨✨,,👉👈💖✨✨✨✨🥺,,👉👈💖💖👉👈💖💖👉👈💖💖✨🥺👉👈✨✨✨,,👉👈💖✨✨✨✨🥺,,,,👉👈💖✨✨✨✨🥺,,👉👈💖💖✨🥺,👉👈💖💖✨,,👉👈💖💖✨,,👉👈💖💖✨🥺,,👉👈💖✨✨✨✨🥺,,,,👉👈💖✨✨✨✨🥺,,,,👉👈💖💖🥺👉👈💖💖✨👉👈✨✨✨✨🥺,,👉👈💖✨✨✨✨🥺,,,👉👈💖💖✨,👉👈💖💖✨🥺,👉👈💖💖✨🥺,👉👈💖💖✨,👉👈💖💖🥺,,,,👉👈
Closes #1786
> docs: add catppuccin/bottom

- README.md
- resources/ports.yml
> docs: add catppuccin/lazygit

- resources/ports.yml
> docs: add catppuccin/stable-diffusion-web-ui

- README.md
- resources/ports.yml
> docs: add catppuccin/vercel

- README.md
- resources/ports.yml
> docs: add catppuccin/hexchat

- README.md
- resources/ports.yml
> docs: add catppuccin/notepad-plus-plus

- README.md
> Add AnuPpuccin in Showcase

- README.md
- resources/ports.yml
> docs: add catppuccin/sidebery

- README.md
- resources/ports.yml
Merge when issue #1807 closes.
> docs: Add Tutanota

- README.md
- resources/ports.yml
> docs: add elk port

- README.md
- resources/ports.yml
> docs: add egui

- README.md
- resources/ports.yml
> docs: add catppuccin/openbox

- README.md
fix a typo in the README.md file
> docs(README): fix a typo

- README.md
- resources/ports.yml
> docs: add catppuccin/solvespace

- README.md
> docs: add Reddit

- README.md
- resources/ports.yml
> docs: add catppuccin/qbittorrent

- README.md
- resources/ports.yml
> docs: add catppuccin/ultrakill

- README.md
- resources/ports.yml
> feat: add matplotlib

- resources/ports.yml
typo in the port name. vscode also autoformatted the file, if you don't like that i'll change it back
> fix: rename sideberry to sidebery in ports.yml

- resources/ports.schema.json
- resources/ports.yml
Since we've got a quite a few games now, it might make sense for them to have their own category.
> docs: add game category

- resources/ports.yml
closes https://github.com/catppuccin/catppuccin/issues/1886
> docs: add catppuccin/twitch

- README.md
- resources/ports.yml
A beautiful tool made by `@nekowinston` !!
> docs(showcase): add faerber

- resources/ports.yml
> docs: add catppuccin/replit

- README.md
- resources/ports.yml
Closes #1910.
Pinging @alaidriel since she's the author :slightly_smiling_face:
> docs: add catppuccin/nixos-search

- README.md
- resources/ports.yml
> feat: add ksyntaxhighlighting

- README.md
- resources/ports.yml
> feat: add dopamine & fluent terminal

- README.md
Added simple mp to the showcase
> docs(showcase): add Simple MP

- README.md
- resources/ports.yml
> docs: add catppuccin/drracket

- resources/ports.yml
> docs: add catppuccin/heroic

- README.md
- resources/ports.yml
> docs: add catppuccin/vscode-icons

- README.md
- resources/ports.yml
> docs: add catppuccin/freshrss

- resources/ports.yml
> docs: add catppuccin/flow-launcher

- README.md
- resources/ports.yml
> docs: add catppuccin/gitea

- README.md
- resources/ports.yml
> docs: add catppuccin/cider

- README.md
- resources/ports.yml
> docs(showcase): add comfy

- README.md
- resources/ports.yml
Added the [PowerPoint Slides](https://github.com/catppuccin/powerpoint-slides) port in the `ports.yml` file and `README.md` file.
> docs(ports): Added PowerPoint Slides port

- README.md
- resources/ports.yml
> docs: add catppuccin/swaync

- README.md
- resources/ports.yml
> docs: add catppuccin/musicbee

- README.md
- resources/ports.yml
> docs: add catppuccin/powershell

- resources/ports.yml
> docs: add catppuccin/pomotroid (#2011)

- docs/style-guide.md
It could have just been the 3rd variant of the colors idk
> docs: fix potential duplicate???

- resources/ports.yml
> docs: add catppuccin/opera-gx

- resources/ports.yml
This is for https://github.com/catppuccin/raycast :)
> feat: add raycast to ports.yml

- resources/ports.yml
> docs: add catppuccin/lua

- resources/ports.yml
[ghostwriter port](https://github.com/catppuccin/ghostwriter)
issue: #2062
> docs: add catppuccin/ghostwriter

- README.md
add a link to the showcase section for my alternative VS Code theme
> add alternative vs code theme to showcase

- resources/ports.yml
> docs: add catppuccin/limine

- resources/ports.yml
> docs: add catppuccin/oldtwitter

- resources/ports.yml
> Docs: Add github-readme-streak-stats

- resources/ports.yml
> docs: add GlazeWM to ports.yml

- resources/ports.yml
> docs: add catppuccin/fleet

- resources/ports.yml
> docs: add skim to ports list

- resources/ports.yml
> docs: add catppuccin/jupyterlab

- resources/ports.yml
> docs: add catppuccin/steam-deck

- .github/workflows/readme.yml
This commit allows the readme.yml to be called by other workflows and manually invoked.
> ci: add `on_workflow_call` & `on_workflow_dispatch`

- resources/ports.yml
> docs: add catppuccin/aseprite

- resources/ports.yml
Hi!
Port has been already transferred to the org: https://github.com/catppuccin/tofi
Issue: #2171 
Thanks in advance!
> doc: add catppuccin/tofi

- samples/cs.cs
Essentially taken from the Rider color scheme settings:
- Will help solve https://github.com/catppuccin/vscode/issues/178
> feat: add C# sample file

- resources/ports.yml
> docs: add catppuccin/qtcreator

- resources/ports.yml
Adding Rio to ports.yml 
Resolves #2138
> docs: add catppuccin/rio

- README.md
> docs: add WCAG 2.1 badge to `README.md`

- resources/ports.yml
> docs: add catppuccin/fitbit

- resources/ports.yml
> docs: add catppuccin/rstudio

- resources/ports.yml
Thanks for the lovely color scheme ~
> docs(showcase): add Mind Elixir

- resources/ports.yml
I got so many compliments about the color theme already. Thanks a ton!
> docs(showcase): add Career Vault

- resources/ports.yml
> docs: add catppuccin/vendetta

- resources/ports.yml
> docs: add catppuccin/sioyek

- samples/c.c
This commit introduces a C code snippet.
> feat: Add C code sample with structs, unions, and memory allocation

- resources/ports.yml
> docs: add catppuccin/fuzzel (#2243)

- resources/ports.yml
> docs: add catppuccin/yakuake

- resources/ports.yml
> docs: add catppuccin/forklift-4

- resources/ports.yml
> docs: add catppuccin/delta

- resources/ports.yml
Adds latex to ports.yml
Reference: #2271
> docs: add catppuccin/latex

- resources/ports.yml
> docs: add catppuccin/yazi

- resources/ports.yml
> docs: add catppuccin/scrivener

- resources/ports.yml
> doc: add serenity os

- resources/ports.yml
> docs: add catppuccin/giscus

- resources/ports.yml
> docs: add catppuccin/mpv

- resources/ports.yml
> docs: add catppuccin/imv

- README.md
It's about time.
(Sorry @pocco81, I'm touching the sacred title :smile:)
> docs(README.md): add IPA pronounciation

- .github/workflows/website.yml
Depends on https://github.com/catppuccin/website/pull/19
Also need to confirm that the token won't be leaked anywhere.
> ci: add deploy hook for website

- docs/style-guide.md
- Enum Variants are `Teal`
- Regex is `Pink`
> docs(style-guide): update editor syntax highlighting

- samples/ruby.rb
Eventually, I'd like to move the samples
directory to another repository. Potentially
catppuccin/toolbox?
> chore(samples): add `ruby.rb`

- resources/ports.yml
> chore(kitty): remove custom icon

- resources/ports.yml
> docs: add catppuccin/hyprlock

- docs/style-guide.md
Definitely not trying to fix my mistakes in #2335...
> docs(style-guide): spaces > tabs

- resources/ports.yml
> docs: add catppuccin/github-file-explorer-icons

- resources/ports.yml
> docs: add catppuccin/chatterino2

- resources/ports.yml
> docs: add catppuccin/mobaxterm

- README.md
- resources/ports.yml
> docs: add catppuccin/fr33zmenu (#2276)

- resources/ports.yml
> docs: add catppuccin/squirrel

- resources/ports.yml
The maintainer is no longer interested in continuing with the work, but is happy to be contacted in case someone else wants to pick up where they left off.
> chore(maintainers): update catppuccin/ui

- resources/ports.yml
> docs: add catppuccin/chroma

- resources/ports.yml
Closes https://github.com/catppuccin/catppuccin/issues/2305
> docs: add catppuccin/ish

- resources/ports.yml
I just edited this file, let me know if I did this right.
CC: @ghostx31
> chore(maintainers): add Matthias to `sublime-text`

- resources/ports.yml
closes https://github.com/catppuccin/catppuccin/issues/2351
> docs: add catppuccin/gh-dash

- resources/ports.yml
Hi, your theme is really beautiful, so I added it to [Reciper](https://github.com/judemont/reciper).
If you want you can add it to the showcases.
Thank you
>  docs(showcase): add Reciper

- resources/ports.yml
> docs: add catppuccin/process-compose

- resources/ports.yml
refs: https://github.com/catppuccin/cider/issues/1, #2396
> chore: remove @nekowinston from cider maintainers

- resources/ports.yml
Most ports should be left in an okay state, Tailwind is probably due for a full rewrite once v4 releases. I never managed to force myself to finish work on the v1 PR, not really happy with the state I'm leaving it in.
Please remove me from any repos where I might still have outside collaborator permissions after I've left the org.
It's been fun.
> chore(maintainers): remove @nekowinston

- resources/ports.yml
As discussed in Discord, follow up to https://github.com/catppuccin/website/pull/69.
> fix: andreasgrafen -> @unseen-ninja

- resources/ports.yml
Uses the correct name/spelling/capitalization as each project itself uses.
> chore(ports.yml): update names

- resources/ports.yml
Our editorconfig specifies that
this file should be 2 spaces.
> style(ports.yml): reformat to 2 spaces

- resources/ports.yml
Fixes: https://github.com/catppuccin/catppuccin/issues/2416
> docs: add catppuccin/elixir

- resources/ports.yml
> docs: add catppuccin/daisyui

- resources/ports.yml
> docs: add catppuccin/chrome-devtools

- resources/ports.yml
> docs: add catppuccin/mixplorer

- resources/ports.yml
Can be reverted depending on the outcome of #2430.
> chore(ports.yml): mark `oldtwitter` as archived

- resources/ports.yml
> docs: add catppuccin/cosmic-desktop

- resources/ports.yml
I either don't use these apps anymore or I no longer have the time to give them the love they deserve.
> chore(maintainers): move @isabelroses to `past-maintainers`

- resources/ports.yml
Closes #2390. No this totally isn't the second time I am sending this in what are you talking about. 
Hopefully next time I am contributing something to catppuccin it is a little less meme-y
> docs: add catppuccin/sent

- resources/ports.yml
> docs: revive catppuccin/aliucord

- resources/ports.yml
i'll need a review on https://github.com/catppuccin/vscode/pull/399 while we're at it 😅
> chore(maintainers): add backwardspy to vscode & co

- resources/ports.yml
> docs: add catppuccin/fnott

- resources/ports.yml
> docs: add catppuccin/windows9x

- resources/ports.yml
As I've changed my github username
> chore(maintainers): `James-McK` -> `autumn-mck`

- resources/ports.yml
https://github.com/catppuccin/emacs/issues/155
> chore(maintainers): add `jtbx` to emacs

- resources/ports.yml
Heya - adding myself to be the new maintainer for the Vimium port [https://discord.com/channels/907385605422448742/907386197855322123/1271005835388125184](url)
Please let me know if I need to do anything else with this PR :)
Cheers!
> chore(maintainers): add `Sebagabones` to vimium

- resources/ports.yml
> docs: add catppuccin/typst

- resources/ports.yml
> docs: add catppuccin/gitkraken

- resources/ports.yml
See https://github.com/catppuccin/latex/pull/5#pullrequestreview-2236551927
> chore(maintainers): add atticus to latex

- resources/ports.yml
> docs: add catppuccin/miniflux

- resources/ports.yml
Been doing a bunch of work on it recently, I'd like to keep maintaining it officially!
> chore(maintainers): add uncenter to flow-launcher

- resources/ports.yml
> docs: add catppuccin/the-archive

- resources/ports.yml
> docs: add catppuccin/vscord

- resources/ports.yml
> docs: add catppuccin/ghostty

- resources/ports.yml
Closes #2374 (well it is already closed but whatever) and #2529.
> docs: add catppuccin/prismjs

- resources/ports.yml
Been doing a lot of work in this port recently, I'd be up for maintaining it in the future.
> chore(maintainers): add uncenter to highlightjs

- resources/ports.yml
> docs: add catppuccin/tumblr

- resources/ports.yml
This PR adds myself to the list of current maintainers for catppuccin/obs and
catppuccin/qbittorrent.
As part of this PR, I'd like to check if @Xurdejl is still interested in being a
maintainer for both of those ports mentioned above. Please respond if you'd like
to stay as a maintainer!
I'll proceed with moving @Xurdejl to the past maintainers list if I don't hear
anything from them in a few weeks.
> chore(maintainers): add @sgoudham to obs and qbittorrent

- resources/ports.yml
Thanks @AngelBerihuete again for your contribution to Catppuccin. I'll be removing you from the organisation after this PR is merged as mentioned in https://github.com/catppuccin/rstudio/pull/1
> chore(maintainers): update maintainers for `rstudio`

- resources/ports.yml
> docs: add catppuccin/kicad

- resources/ports.yml
> docs: add catppuccin/where-is-my-sddm-theme

- resources/ports.yml
> docs: add catppuccin/libreoffice

- resources/ports.yml
See https://github.com/catppuccin/chrome-devtools/pull/12.
> docs: archive catppuccin/chrome-devtools

- resources/ports.yml
Closes https://github.com/catppuccin/catppuccin/issues/2544
> docs: add catppuccin/zen-browser

- resources/ports.yml
@89iuv it was a joy working with you, best of luck.
> chore(maintainers): move `vdbe` to past-maintainers for tmux

- resources/ports.yml
Adds [Catbbrew](https://catbbrew.com/) to the showcases
> docs(README): add `catbbrew` to showcase section

- resources/ports.yml
> docs: add catppuccin/ruby

- resources/ports.yml
> docs: add catppuccin/ohmyrepl

- resources/ports.yml
Might as well be explicit about it.
> chore(maintainers): add @sgoudham to some ports

- resources/ports.yml
Very appreciative for the chance to be part of this.
> chore(visual-studio): move @djflan to past maintainers

- resources/ports.yml
Add catppuccin/asciinema
Closes #2104
> docs: add catppuccin/asciinema

- resources/ports.yml
> docs: add catppuccin/symfonium

- resources/ports.yml
> docs: add catppuccin/wlogout

- resources/ports.yml
> docs: add catppuccin/zed-icons

- resources/ports.yml
Closes #2635.
https://github.com/catppuccin/television
> docs: add catppuccin/television

- resources/ports.yml
Marks the merge of https://github.com/catppuccin/catppuccin/issues/2641#issuecomment-2685820270 into the organization
> docs: add catppuccin/nushell

- resources/ports.yml
Closes #2659.
https://github.com/catppuccin/canva
> docs: add catppuccin/canva

- resources/ports.yml
This maintainer has notified that they no longer have the time to maintain
home-assistant. @fapfaff - am I right in assuming that you no longer are
interested in maintaining refind too?
I'll eventually merge if I don't hear a response in a few days.
Thanks again for your contributions.
> chore(maintainers): move `@fapfaff` to past-maintainers

- resources/ports.yml
> docs: add catppuccin/jellyfin

- resources/ports.yml
> chore(maintainers): add @zspher to `obs`

- docs/style-guide.md
macro style from https://github.com/catppuccin/catppuccin/issues/2651
diff styles chosen in https://github.com/catppuccin/notepad-plus-plus/pull/39
> docs: add macro and diff colours to style guide

- resources/ports.yml
> docs: add catppuccin/ncspot

- resources/ports.yml
Hey @kuromedayo 👋,
If I'm remembering correctly, you were interested in becoming a maintainer for fcitx5? If that's still the case, please accept the org invitation which should have been sent to your email and I'll grant you maintainer permissions.
Thanks!
> chore(fcitx5): add @kuromedayo to `current-maintainers`

- resources/ports.yml
> chore(imhex): move @DorielRivalet to `past-maintainers`

- resources/ports.yml
> docs: add catppuccin/starlight

- resources/ports.yml
> docs: add catppuccin/atuin

- resources/ports.yml
Category to be changed in #2762
> docs: add pygments

- resources/ports.yml
> docs: add catppuccin/file-pilot

- resources/ports.yml
Adding myself as the COSMIC Desktop theme maintainer
> chore(cosmic-desktop): add @HeitorAugustoLN to `current-maintainers`

- resources/ports.yml
> docs: add catppuccin/mangohud

- resources/ports.yml
> docs: add catppuccin/yomitan

- resources/ports.yml
> docs: add catppuccin/keybr

- resources/ports.yml
> docs: add catppuccin/vtop

- resources/ports.yml
> docs: add catppuccin/gnome-text-editor

- resources/ports.yml
adding myself to the neovim maintainers
> chore(nvim): add @comfysage to `current-maintainers`

- resources/ports.yml
> docs: add catppuccin/shadcn-ui

- README.md
- resources/ports.yml
Closes #2821 
How do I supply a custom icon? Here's a good one from [papirus-icon-theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/32x32/apps/renoise.svg).
> docs: add catppuccin/renoise

- resources/ports.yml
> docs: add catppuccin/unocss

- resources/ports.yml
> docs: add catppuccin/sql-server-management-studio

- resources/ports.yml
> docs: add catppuccin/coteditor

- samples/haskell.hs
This richer Haskell sample helps when doing Haskell-specific adjustments in catppuccin ports, e.g. https://github.com/catppuccin/vscode/pull/559.
> chore(samples): improve Haskell code sample

- resources/ports.yml
> docs: add catppuccin/jenkins

- resources/ports.yml
Closes #2874 
* Add ankddev as collaborator/maintainer
* Add eza to port list
> docs: add catppuccin/eza

- resources/ports.yml
project appears to have been deleted
> docs(showcase): remove ccrs

- resources/categories.yml
> chore: fix typos across codebase
